export const SET_SKIN ="SET_SKIN";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER = "REGISTER";
export const SIGN_IN ="SIGN_IN";
export const SIGN_IN_FAILED ="SIGN_IN_FAILED";

export const UPDATE_CONTACT="UPDATE_CONTACT"
export const UPDATE_CONTACT_ERROR="UPDATE_CONTACT_ERROR"
export const UPDATE_SKIN="UPDATE_SKIN"
export const UPDATE_SKIN_ERROR="UPDATE_SKIN_ERROR"
export const ADD_CONTACT="ADD_CONTACT"
export const ADD_CONTACT_ERROR="ADD_CONTACT_ERROR"


export const ADD_EDUCATION="ADD_EDUCATION"
export const ADD_EDUCATION_ERROR="ADD_EDUCATION_ERROR"
export const UPDATE_EDUCATION="UPDATE_EDUCATION"
export const UPDATE_EDUCATION_ERROR="UPDATE_EDUCATION_ERROR"

export const SIGN_OUT ="SIGN_OUT";